### ISSUE TITLE
how to change google search plus open in tab not in new windows? #1113

### ISSUE THREAD

**Issue by ghost** [jjw24/Wox.Plugin.GoogleSearch#4]
how to change google search plus open in tab not in new windows? #1113

**Comment by jjw24** [comment]
Hi @ThomasQAQOUO , sorry for the late reply, I will look to implement this.

**Comment by oliviercarizzoni** [comment]
I confirm this a useful enhancement I am looking for as well, thanks for the plugin @jjw24

**Comment by jjw24** [comment]
Will work on this soon

**Comment by ThomasQAQOUO** [comment]
thanks very much😂😂😂

Jeremy Wu ***@***.***> 于 2022年9月24日周六 下午2:00写道：

**Comment by jjw24** [comment]
Hi, please update to v2.0.0, should be available in the next couple of hours. This update will allow the plugin to open based on your tab/new window browser preference in Flow's settings.

**Comment by oliviercarizzoni** [comment]
Working perfectly, thanks @jjw24 you're the best !
