### ISSUE TITLE
Searching is not working with HTTP Proxy Enabled in Flow Launcher

### ISSUE THREAD

**Issue by Traxmaeus** [jjw24/Wox.Plugin.GoogleSearch#8]
Hey @jjw24, first of all I wanted to say that the port of **GoogleSearchPlus** for **FlowLauncher** is amazing!

Although I've encountered one big issue.

In Flow Launcher there is an option to use HTTP Proxy, which I would like to use for changing my query suggestions in Google Search
to a different country. When I enable HTTP Proxy and test it (configured correctly), The classic WebSearch query suggestions
are giving me results based on the server location of that Proxy, but the GoogleSearchPlus gets broken and is not giving any results/suggestions.

Do you know any workaround for this issue or it's straight not possible with the ported version of this Plugin?

Thank you in forward and have a great day!

**Comment by jjw24** [comment]
Hi there, if WebSearch is working as it's intended with proxy enabled, I can take a look at its code and update GoogleSearch to do the same. Without having a look, I suspect GoogleSearch maybe not using/ honouring proxy configuration from flow.

**Comment by jjw24** [comment]
A fix has been added to get the plugin working again, not sure if this has solved your problem also, please test it out and let me know. Will close this issue in the meantime and reopen if problem persists.
